-- begin PLANNER2_SESSION
alter table PLANNER2_SESSION add constraint FK_PLANNER2_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNER2_SPEAKER(ID)^
create index IDX_PLANNER2_SESSION_ON_SPEAKER on PLANNER2_SESSION (SPEAKER_ID)^
-- end PLANNER2_SESSION
-- begin PLANNER2_SPEAKER
create unique index IDX_PLANNER2_SPEAKER_UK_EMAIL on PLANNER2_SPEAKER (EMAIL) where DELETE_TS is null ^
-- end PLANNER2_SPEAKER
