alter table PLANNER2_SESSION add constraint FK_PLANNER2_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNER2_SPEAKER(ID);
create index IDX_PLANNER2_SESSION_ON_SPEAKER on PLANNER2_SESSION (SPEAKER_ID);
